# Numpy Nedir?

 

*   Numpy, Python programlama dilinde matematiksel işlemleri ve çok boyutlu dizileri işlemek için kullanılan bir kütüphanedir.

*   Numpy, hızlı ve etkili hesaplamalar için gelişmiş veri yapıları ve matematiksel fonksiyonlar sağlar.





# Numpy Dizilerini Oluşturma



*   Numpy dizileri, homojen veri tiplerini tutabilen ve hızlı matematiksel işlemler yapabilen çok boyutlu dizilerdir. Numpy kütüphanesindeki en önemli veri yapısı olan ndarray (N-dimensional array), bu dizileri temsil eder.

Numpy dizilerini oluşturmak için çeşitli yöntemler vardır.

Listelerden Numpy Dizisi Oluşturma:
Numpy dizileri, bir Python listesinden np.array() fonksiyonu kullanılarak oluşturulabilir. Bu fonksiyon, bir liste veya başka bir diziyi alır ve onu Numpy dizisine dönüştürür.






In [1]:
import numpy as np

# Liste üzerinden numpy dizisi oluşturma
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)


[1 2 3 4 5]




*  Sıfırlardan Numpy Dizisi Oluşturma:
Numpy, belirli bir boyutta sıfırlardan oluşan bir dizi oluşturmak için np.zeros() fonksiyonunu sağlar. Bu fonksiyon, belirtilen boyutlara sahip bir dizi oluşturur ve tüm elemanları sıfır değerine ayarlar.


In [ ]:
import numpy as np

zeros_arr = np.zeros((3, 4))




*  Birlerden Numpy Dizisi Oluşturma:
Numpy, belirli bir boyutta birlerden oluşan bir dizi oluşturmak için np.ones() fonksiyonunu sağlar. Bu fonksiyon, belirtilen boyutlara sahip bir dizi oluşturur ve tüm elemanları bir değerine ayarlar.



In [ ]:
import numpy as np

ones_arr = np.ones((2, 3))




*   Belirli Değerlerle Numpy Dizisi Oluşturma:
Numpy, belirli bir boyutta belirli bir değerle doldurulmuş bir dizi oluşturmak için np.full() fonksiyonunu sağlar. Bu fonksiyon, belirtilen boyutlara sahip bir dizi oluşturur ve tüm elemanları belirtilen değere ayarlar.

In [ ]:
import numpy as np

value_arr = np.full((2, 2), 5)



*   Aralıklı Değerlerle Numpy Dizisi Oluşturma:
Numpy, belirli bir aralıktaki değerlerle doldurulmuş bir dizi oluşturmak için np.arange() fonksiyonunu sağlar. Bu fonksiyon, belirli bir başlangıç değerinden başlayarak belirli bir adımla artan veya azalan bir dizi oluşturur.


In [ ]:
import numpy as np

range_arr = np.arange(0, 10, 2)



# Numpy Dizilerinde İndeksleme ve Dilimleme



1.   Numpy dizilerinde elemanlara erişmek ve dilimlemek için indeksleme ve dilimleme yöntemlerini kullanabiliriz.
2.   Dizi indeksleri sıfırdan başlar ve köşeli parantez içinde belirtilir.

Numpy dizilerinde indeksleme:

Numpy dizilerindeki her bir eleman, sıfırdan başlayan bir indeksleme sistemi kullanılarak erişilebilir. Yani, dizinin ilk elemanı indeks 0'dır, ikinci elemanı indeks 1'dir ve böyle devam eder.
İndeksleme için dizinin adını köşeli parantez içine alarak istenen indeksi belirtmek yeterlidir. Örneğin, arr[0] ifadesi, dizinin ilk elemanına erişmek için kullanılır.
Numpy dizileri çok boyutlu olabileceğinden, indekslerin her bir boyutta belirtilmesi gerekir. Örneğin, iki boyutlu bir dizi için arr[0, 1] ifadesi, ilk satırın ikinci elemanına erişmek için kullanılır.
Numpy dizilerinde dilimleme:

Dilimleme, bir dizinin belirli bir aralığındaki elemanlara erişmek için kullanılan bir yöntemdir.
Dilimleme işlemi için iki nokta üst üste (:) kullanılır. Başlangıç ve bitiş indeksleri belirtilirken bu iki nokta kullanılır. Örneğin, arr[2:5] ifadesi, dizinin 2. indeksten 5. indekse kadar olan elemanlarını içeren bir dilim oluşturur.
Dilimleme işleminde başlangıç ve bitiş indeksleri dahil değildir. Yani, arr[2:5] ifadesi, 2. indeksten başlayarak 4. indekse kadar olan elemanları içerir, ancak 5. indeksi içermez.
Dilimleme işlemi aynı zamanda çok boyutlu diziler için de kullanılabilir. Örneğin, iki boyutlu bir dizi için arr[:, 1:3] ifadesi, tüm satırları ve 1. ile 2. indeksler arasındaki sütunları içeren bir dilim oluşturur.



In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# İndeksleme
print(arr[0])  # İlk eleman
print(arr[2])  # 3. eleman

# Dilimleme
print(arr[1:4])  # 2. elemandan 4. elemana kadar (dahil değil)


1
3
[2 3 4]


# Numpy Matematiksel İşlemler

*   Numpy, matematiksel işlemler için bir dizi fonksiyon sağlar.
*   Temel matematiksel işlemler (toplama, çıkarma, çarpma, bölme) yanı sıra trigonometrik, logaritmik ve istatistiksel işlemleri yapabiliriz.






In [ ]:
import numpy as np

# Temel matematiksel işlemler
arr = np.array([1, 2, 3, 4, 5])

# Toplama
print("Toplama:", np.add(arr, 2))

# Çıkarma
print("Çıkarma:", np.subtract(arr, 2))

# Çarpma
print("Çarpma:", np.multiply(arr, 2))

# Bölme
print("Bölme:", np.divide(arr, 2))

# Trigonometrik fonksiyonlar
arr_rad = np.radians(arr)  # Dereceleri radyanlara dönüştürmek için
print("Sinüs:", np.sin(arr_rad))
print("Kosinüs:", np.cos(arr_rad))
print("Tanjant:", np.tan(arr_rad))

# Logaritmik fonksiyonlar
print("Logaritma (taban 10):", np.log10(arr))
print("Doğal Logaritma:", np.log(arr))




# Numpy Yaygın Fonksiyonlar



*   Numpy, yaygın olarak kullanılan istatistiksel işlemleri yapmak için bir dizi fonksiyon sağlar.
*   Bunlar arasında np.mean(), np.max(), np.min(), np.sum() gibi fonksiyonlar bulunur.








In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Ortalama
print(np.mean(arr))

# Maksimum değer
print(np.max(arr))

# Minimum değer
print(np.min(arr))

# Toplam
print(np.sum(arr))
# İstatistiksel işlemler
arr2 = np.array([3, 1, 5, 2, 4])
print("Ortalama:", np.mean(arr2))
print("Maksimum Değer:", np.max(arr2))
print("Minimum Değer:", np.min(arr2))
print("Toplam:", np.sum(arr2))
print("Standart Sapma:", np.std(arr2))
print("Varyans:", np.var(arr2))
print("Medyan:", np.median(arr2))

# Numpy Dizilerinin Şekil ve Boyutları

*   Numpy dizileri, şekil ve boyutları üzerinde çalışmak için işlevler sağlar.
*   Dizi şeklini değiştirmek, yeniden şekillendirmek ve birleştirmek gibi işlemleri yapabiliriz.


Numpy dizileri, çok boyutlu diziler olarak adlandırılan ve homojen veri tiplerini tutabilen veri yapılarıdır. Bu dizilerin şekli (shape) ve boyutu (dimension) dizinin yapısını tanımlar.

Şekil (shape):
Numpy dizilerinin şekli, her boyuttaki eleman sayısını belirtir. Örneğin, 1 boyutlu bir dizi şekli (5,), 5 elemana sahip olduğunu ifade eder. 2 boyutlu bir dizi şekli (3, 4) ise 3 satır ve 4 sütundan oluştuğunu ifade eder. Daha karmaşık dizilerde ise şekil, boyutlara göre uzunluğu değişen bir demet olarak temsil edilir.

Boyut (dimension):
Numpy dizilerinin boyutu, dizinin içerdiği eksen sayısını belirtir. Örneğin, 1 boyutlu bir dizi 1 boyuta (vektör), 2 boyutlu bir dizi 2 boyuta (matris) sahiptir. 3 boyutlu bir dizi ise 3 boyutta veri depolar. Boyut sayısı, aynı zamanda şeklin boyutunu belirler.

Numpy dizilerinde şekil ve boyutları değiştirmek için bazı işlevler ve yöntemler mevcuttur. Örneğin, reshape() işlevi, bir dizinin şeklini değiştirmek için kullanılır. Bu işlem, veri yapısını koruyarak diziyi yeniden şekillendirmeye olanak tanır. Diğer bir yöntem olan resize() ise, bir diziyi belirli bir şekle yeniden boyutlandırmak için kullanılır. Bu yöntemde, veri yapısı değiştirilebilir.

Ayrıca, yeni boyutlar eklemek veya mevcut boyutları azaltmak için np.newaxis kullanılabilir. Bu, dizinin boyutunu değiştirmek için kullanılan güçlü bir araçtır.






In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Dizinin şeklini değiştirme
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

# Dizileri birleştirme
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Mantıksal numpy dizisi (Boolean array), numpy dizisinin her bir elemanının True (doğru) veya False (yanlış) değerine sahip olduğu bir dizi türüdür. Bu tür diziler, mantıksal operasyonları ve koşullu işlemleri uygulamak için kullanılır.

Numpy dizilerini mantıksal dizilere dönüştürmek için genellikle bir koşul ifadesi kullanılır. Koşul ifadesi, her bir dizi elemanı üzerinde bir karşılaştırma yapar ve sonucunda True veya False değeri döner. Bu sonuçlar, mantıksal dizinin elemanları olur.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Koşul ifadesi: arr dizisindeki elemanların 3'ten büyük olup olmadığını kontrol ediyoruz
condition = arr > 3

print(condition)


[False False False  True  True]
